### ISSUE TITLE
About the UCF-HMDB_full Dataset

### ISSUE THREAD

**Issue by stefanxinhong** [cmhungsteve/TA3N#1]
Where can I download the UCF-HMDB_full dataset used in the paper?

**Comment by cmhungsteve** [comment]
sorry for the late response. 
I am busy with a paper deadline.
I will release the dataset once I finish the paper submission.

**Comment by cmhungsteve** [comment]
they're uploaded.

**Comment by stefanxinhong** [comment]
Can you provide the data list files for UCF-HMDB_full  in the ICCV paper? I have noticed that the released HDMB-features dataset is larger than dataset used in the paper. ie, 840 training videos and 360 validation videos from HMDB.

**Comment by cmhungsteve** [comment]
You should be able to generate the data list files using `script_list2DA.sh` for the UCF-HMDB_full dataset. 
I didn't provide the data list files because they depend on where you place the dataset. You still need to manually edit a lot even if you have my data list files.
We are still working on releasing the Kinetic-Gameplay dataset since there are some copyright issues.
