### ISSUE TITLE
Code for obtaining the baseline results.

### ISSUE THREAD

**Issue by AadSah** [cmhungsteve/TA3N#23]
Hi @cmhungsteve 

Thanks for the great work. I wanted to execute and obtain the baseline results mentioned in the paper (DANN + [TempPooling/TempRelation]), can you please let me know if you can make the code public?

Thanks

**Comment by cmhungsteve** [comment]
DANN + TemPooling:
`frame_aggregation=avgpool`
`use_target=uSv`
`adv_DA=RevGrad`

DANN + TemRelation:
`frame_aggregation=trn-m`
`use_target=uSv`
`adv_DA=RevGrad`

and set other `XXX_DA` as `none`.

**Comment by AadSah** [comment]
Thanks a lot @cmhungsteve 
It would be great if you could also share the arguments for obtaining the 'source-only' and 'target-only' results. :)

**Comment by cmhungsteve** [comment]
Just set `use_target=none`, and then modify `dataset_source`.
For example, if you are working on `hmdb_ucf` and want to train and test on ucf101 only, then set `dataset_source=ucf101`, otherwise set `dataset_source=hmdb51`.
In another word, this all depends on how you define your source and target datasets.

**Comment by avijit9** [comment]
Do I need to set `use_attn` to none when reproducing DANN results from 3, 4, 5?

**Comment by cmhungsteve** [comment]
Yes
